#!/bin/bash

# usage:
# code-edit <slug>

set -o errexit

[[ -z $1 ]] && { echo error; exit 1; }

slug=$1
club=$( echo $slug | cut -d'/' -f1 )
repo=$( echo $slug | cut -d'/' -f2 )
[[ $slug == */* ]] || club=$GITHUB_USERNAME
slug=$club/$repo

[[ -d ~/desktop/code/$slug ]] || code-clone $slug

cd ~/desktop/code/$slug

[[ -f ./script/start ]] || code . --reuse-window && ./script/start

exit
