#!/bin/bash

# usage:
# code-clone <slug> && code-edit $_

set -o errexit

[[ -z $1 ]] && { echo error; exit 1; }

slug=$1
club=$( echo $slug | cut -d'/' -f1 )
repo=$( echo $slug | cut -d'/' -f2 )
[[ $slug == */* ]] || club=$GITHUB_USERNAME
slug=$club/$repo

cd ~/desktop/code

mkdir --parents $club && cd $_

git clone $( forge-url-gh $slug )

cd $repo

[[ -f ./script/profile/$PROFILE/remote ]] && bash ./script/profile/$PROFILE/remote
