#!/bin/bash

# usage:
# data-push <path> [--dryrun]

set -o errexit

mkdir --parents ~/desktop/data/data.subhelion.com

aws --profile data.subhelion.com s3 sync ~/desktop/data/data.subhelion.com/$1 s3://data.subhelion.com/$1 $2
