#!/bin/bash

# usage:
# data-pull <path> [--dry-run]

set -o errexit

mkdir --parents ~/desktop/data/data.subhelion.com

aws --profile data.subhelion.com s3 sync s3://data.subhelion.com/$1 ~/desktop/data/data.subhelion.com/$1 $2
